### ISSUE TITLE
今天开始无法使用，大家一样吗。

### ISSUE THREAD

**Issue by haso2007** [aurora-develop/Duck2api#12]
返回信息
{
    "error": {
        "code": "error",
        "message": null,
        "param": null,
        "type": "418 I'm a teapot"
    }
}

**Comment by denniszlei** [comment]
我也不行，分别在韩国&美国两台vps上试过，同样的"418 I'm a teapot"错误

**Comment by vawterdada** [comment]
我也是，昨天还好好的

**Comment by xxclbkmmx** [comment]
不能用了+1 418报错

**Comment by li-linfeng** [comment]
+1

**Comment by haso2007** [comment]
只能用chat2api先用着，不过速度确实差太多了。

**Comment by QAbot-zh** [comment]
+1

**Comment by molezz** [comment]
cy

**Comment by Simonmxy** [comment]
不能用了+1

**Comment by igeekbb** [comment]
一样418

**Comment by xxclbkmmx** [comment]
> 一样418

熟悉的头像

**Comment by ffreemt** [comment]
```
"message": {
        "role": "assistant",
        "content": ""
      }
```
我这倒是不出错，但返回`content`是空的

**Comment by learnLi** [comment]
418的响应已修复。

**Comment by ffreemt** [comment]
感谢大佬！ /v1/models 只显示 claude-3-haiku-20240307 和 gpt-3.5-turbo
但实测 llama-3-70b 和 model=mixtral-8x7b 也可以接口用

**Comment by tisfeng** [comment]
ok，我刚补充了 /v1/models  接口数据，它返回的是 duckduckgo 接口数据原始模型名字 https://github.com/aurora-develop/Duck2api/pull/13 。

为方便使用，我们对这些模型名做了简单映射，v1/chat/completions 接口可以使用原始模型名，也可以使用如下模型映射名：

gpt-3.5-turbo
claude-3-haiku
llama-3-70b
mixtral-8x7b

<img width="1226" alt="image" src="https://github.com/aurora-develop/Duck2api/assets/25194972/e69dadec-81c0-4450-be84-0912dfb3db5a">

**Comment by ffreemt** [comment]
太感谢了。不知道能不能设一个环境变量自定义接口的前缀？

提这个奇怪的要求是因为duck2go 可以利用 Dockerfile 部署到 huggingface，但 huggingface 禁了以 v1 开头的路由，所以没法调用接口。

原 llm red team 的 https://github.com/LLM-Red-Team/deepseek-free-api 也是以v1开头不能调用接口。但改了一下就可以用了，参看 https://huggingface.co/spaces/mikeee/redteam-deepseek/tree/main/src/api/routes  里几个文件的路由
```
// prefix: '/v1/chat',
prefix: '/hf/v1/chat',
```

**Comment by learnLi** [comment]
> 太感谢了。不知道不能建立一个环境变量自定义接口的前缀？
> 
> 提这个奇怪的要求是因为duck2go可以使用Dockerfile部署到huggingface，但是huggingface禁止了以v1开头的路由，所以没有法调用接口。
> 
> 原 llm red team 的https://github.com/LLM-Red-Team/deepseek-free-api也是以v1开头不能调用接口。但改进了一下就可以用了，参考https://huggingface.co/spaces/mikeee/redteam-deepseek/tree/main/src/api/routes 里几个文件的路由
> 
> ```
> // prefix: '/v1/chat',
> prefix: '/hf/v1/chat',
> ```

加了一个PREFIX参数。应该能满足你的需求

**Comment by ffreemt** [comment]
太好了，非常感谢！
