### ISSUE TITLE
又开始无法使用了

### ISSUE THREAD

**Issue by karllee830** [aurora-develop/Duck2api#14]
如同 https://github.com/aurora-develop/Duck2api/issues/12 一样，无法使用。

**Comment by molezz** [comment]
duck开始发力清理了吗 ？

**Comment by karllee830** [comment]
> duck开始发力清理了吗 ？

@molezz 测试了下，继续修改tls_client.WithClientProfile一项就能恢复使用，怀疑duckduckgo可能根据这个来抓特征来屏蔽。

如果想更稳妥的用建议还是自己fork一下仓库，手动修改tls_client.WithClientProfile一项自己用，避免被抓特征。

**Comment by learnLi** [comment]
等新版吧。大家用的同一个指纹，duckgo要关注指纹也是没有办法的。

**Comment by ffreemt** [comment]
喔趣，瞎改成11，居然真的可以了！

**Comment by nobodysclown** [comment]
NextChat 禁用 “注入系统级提示信息”
