### ISSUE TITLE
Render部署被禁了

### ISSUE THREAD

**Issue by haso2007** [aurora-develop/Duck2api#16]
Please review the changes to apply below. All future updates to [render.yaml](https://docs.render.com/blueprint-spec) will be synced automatically.
You can learn more about Render's infrastructure-as-code [here](https://docs.render.com/infrastructure-as-code).

Create web service duck2api
(invalid repository)
自家部署的没有ssl

**Comment by xiaozhou26** [comment]
render封禁这些，正常

**Comment by geek2024811** [comment]
我也是

**Comment by leafmoes** [comment]
试试这个？
[DDG-Chat](https://github.com/leafmoes/DDG-Chat)
