### ISSUE TITLE
/web页面一直等待，打不开

### ISSUE THREAD

**Issue by windtraceQ** [aurora-develop/Duck2api#19]
大部分文件 CORS error

**Comment by Swim0o0** [comment]
就是，一直在这个等待界面
![Snipaste_2024-07-31_19-42-06](https://github.com/user-attachments/assets/50468e9c-c0f3-424a-9bf8-265e58abe745)

**Comment by xiaozhou26** [comment]
大概是web的问题

**Comment by xiaozhou26** [comment]
确实是静态的cdn寄了，已更新。。

**Comment by Swim0o0** [comment]
> 确实是静态的cdn寄了，已更新。。

大佬，可以了吗？我这里还是一直停留在加载界面

**Comment by Swim0o0** [comment]
![Uploading Snipaste_2024-07-31_22-05-56.jpg…]()

**Comment by Swim0o0** [comment]
![Snipaste_2024-07-31_22-05-56](https://github.com/user-attachments/assets/27477f04-c588-4c77-9866-16588136d2b1)

**Comment by Swim0o0** [comment]
![Snipaste_2024-07-31_22-05-56](https://github.com/user-attachments/assets/785b2e90-d8a5-4f09-be3d-86d30541dc3f)

**Comment by xiaozhou26** [comment]
> ![Snipaste_2024-07-31_22-05-56](https://private-user-images.githubusercontent.com/89305852/353863045-785b2e90-d8a5-4f09-be3d-86d30541dc3f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzkxNzEsIm5iZiI6MTcyMjQzODg3MSwicGF0aCI6Ii84OTMwNTg1Mi8zNTM4NjMwNDUtNzg1YjJlOTAtZDhhNS00ZjA5LWJlM2QtODZkMzA1NDFkYzNmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE1MTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YWI3MjQzNzVjNDQyMGEwZjJmOGMyMDQ3ODljZWJjN2RmMTkyOTMyY2NlYzJhY2VlMDg5NjJhYWU1ZGUxYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oJZRoK947Z-2dn_6b9ImKeWVnSK7lmsj8BG3Q-Gk-DE)

重新更新镜像
