### ISSUE TITLE
可能后端已经回滚到gpt3.5了

### ISSUE THREAD

**Issue by vinsec** [aurora-develop/Duck2api#26]
<img width="1497" alt="image" src="https://github.com/user-attachments/assets/301620d7-cdc3-4891-90eb-743eb4bbc456">

废了兄弟们，duck可能偷偷降级了。上周问还是gpt4o的

为什么发现这个呢？因为某个chat聊天接口软件一直报418 非常诡异

**Comment by xiaozhou26** [comment]
![image](https://github.com/user-attachments/assets/31287a5d-7274-41c4-9e26-264e00436afe)
后端还是4o-min，现在3.5比4o min贵，有可能是oai阉割了

**Comment by QAbot-zh** [comment]
啊应该是 oai 降智吧，duck 没必要回滚到一个更贵的模型上吧

**Comment by xiaozhou26** [comment]
目前测试智商还是4o min的

**Comment by vinsec** [comment]
@QAbot-zh @xiaozhou26 
逻辑上是这样，但是我这边测试确实不太对劲。

gpt-4o-mini 的官方接口（包括github copilot chat）都是能够稳定给出正确的模型名(gpt-4o-mini)的，而不是说gpt3.5。

我现在不管是直接在duck-ai那里测，还是通过duck2api，看着大概率都是已经降级到gpt3.5/turbo了。

**Comment by QAbot-zh** [comment]
> @QAbot-zh @xiaozhou26 逻辑上是这样，但是我这边测试确实不太对劲。
> 
> gpt-4o-mini 的官方接口（包括github copilot chat）都是能够稳定给出正确的模型名(gpt-4o-mini)的，而不是说gpt3.5。
> 
> 我现在不管是直接在duck-ai那里测，还是通过duck2api，看着大概率都是已经降级到gpt3.5/turbo了。

直接问是什么模型能不能回答上来取决于它的提示词有没有注入，不靠谱的，还是应该看智力题检测

**Comment by vinsec** [comment]
<img width="1283" alt="image" src="https://github.com/user-attachments/assets/6232d613-b509-4878-bf26-18c4ddfb194f">
<img width="1197" alt="image" src="https://github.com/user-attachments/assets/e283e2ca-356f-4a38-b3fd-16ea53f24545">

@xiaozhou26 不知道开发者有没有用过这个ChatGPTNextWeb套壳软件，上周还是ok的，这几天持续稳定地报418错误（没更新客户端版本）。我看了后端docker的日志，没看出任何问题。在其他地方使用curl是没问题的。

ChatGPTNextWeb向后端发送的请求看着和curl是一致的，格式也ok。不清楚那里出了问题。另一个套壳工具chatbox目前是可以用的。

**Comment by xiaozhou26** [comment]
> @QAbot-zh @xiaozhou26 逻辑上是这样，但是我这边测试确实不太对劲。
> 
> gpt-4o-mini 的官方接口（包括github copilot chat）都是能够稳定给出正确的模型名(gpt-4o-mini)的，而不是说gpt3.5。
> 
> 我现在不管是直接在duck-ai那里测，还是通过duck2api，看着大概率都是已经降级到gpt3.5/turbo了。

直接问是最不靠谱的，直接问经典问题测试即可

**Comment by xiaozhou26** [comment]
> <img alt="image" width="1283" src="https://private-user-images.githubusercontent.com/22928057/358894029-6232d613-b509-4878-bf26-18c4ddfb194f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5ODc2OTcsIm5iZiI6MTcyMzk4NzM5NywicGF0aCI6Ii8yMjkyODA1Ny8zNTg4OTQwMjktNjIzMmQ2MTMtYjUwOS00ODc4LWJmMjYtMThjNGRkZmIxOTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDEzMjMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjN2VmMTY1MTNmMzU0ZGQwZmJiZDA4YjY3Y2Q2OGFmMDI4MWM5YjNmYzc0OWZhNmY3MDhlZTVlOTAwNTYyOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pSS_QqPEJZaMKx9dXGyZyybEoI3-nBWMirpIrFxEHsw"> <img alt="image" width="1197" src="https://private-user-images.githubusercontent.com/22928057/358894097-e283e2ca-356f-4a38-b3fd-16ea53f24545.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5ODc2OTcsIm5iZiI6MTcyMzk4NzM5NywicGF0aCI6Ii8yMjkyODA1Ny8zNTg4OTQwOTctZTI4M2UyY2EtMzU2Zi00YTM4LWIzZmQtMTZlYTUzZjI0NTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDEzMjMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMjMxOTE1ZjAyZWQ1OGM5Y2NmZmEzM2YxNTQ3MWI3MzJlODNkMTAxYjkxY2VjYzVlMzc1N2Y5ZmYwNjdiM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w3H5wXJQPX-kkMH-kewC2eQgLhwnrkS_RO0XNOuh884">
> @xiaozhou26 不知道开发者有没有用过这个ChatGPTNextWeb套壳软件，上周还是ok的，这几天持续稳定地报418错误（没更新客户端版本）。我看了后端docker的日志，没看出任何问题。在其他地方使用curl是没问题的。
> 
> ChatGPTNextWeb向后端发送的请求看着和curl是一致的，格式也ok。不清楚那里出了问题。另一个套壳工具chatbox目前是可以用的。

这个前端项目默认的系统提示词被风控了，duckduckgo官方很幽默，给你返回一个有趣的回答

**Comment by ghost** [comment]
如前面提到的，把“注入系统级提示信息” 给注释掉就可以了。
