### ISSUE TITLE
网关错误或超时

### ISSUE THREAD

**Issue by Dyinglight5** [aurora-develop/Duck2api#27]
云服务器上部署，用了一天第二天回答就显示网关错误或超时
![image](https://github.com/user-attachments/assets/6635e3cd-7c7c-4ba9-99b9-9e3ee9e5addf)

**Comment by QAbot-zh** [comment]
重开试试呢，跑了很久，没发现类似问题

**Comment by Dyinglight5** [comment]
删除聊天记录强制刷新一下就正常了

**Comment by xiaozhou26** [comment]
你估计用的不是这个项目的api，哪里来的flask

**Comment by Dyinglight5** [comment]
> 你估计用的不是这个项目的api，哪里来的flask

那是我提问的问题哈哈
