### ISSUE TITLE
当请求的消息包含 system prompt 时，会返回 418 错误。

### ISSUE THREAD

**Issue by yjmp14** [aurora-develop/Duck2api#29]
例如，请求消息：
`"messages": [
        {
            "role": "system",
            "content": "You are ChatGPT, a large language model trained by OpenAI."
        },
        {
            "role": "user",
            "content": "你好"
        }
    ]`

会报错：
`{
    "error": {
        "message": "bad response status code 418 (request id: 2024091220404672641902693957528)",
        "type": "upstream_error",
        "param": "418",
        "code": "bad_response_status_code"
    }
}`

**Comment by xiaozhou26** [comment]
#30
