### ISSUE TITLE
{“error”:“Unauthorized”}

### ISSUE THREAD

**Issue by ZYWNB666** [aurora-develop/Duck2api#5]
请问，需要配置什么吗？我在阿里云东京地区的serverless上测试的好像不太行，curl的返回结果是{“error”:“Unauthorized”}
我没有配置任何变量
![image](https://github.com/aurora-develop/Duck2api/assets/104631531/82177bb6-0474-4558-a2e9-3cd4ef0444a4)

**Comment by xiaozhou26** [comment]
未授权重新部署试一下
