### ISSUE TITLE
前端页面如何设置密码

### ISSUE THREAD

**Issue by akang943578** [aurora-develop/Duck2api#9]
现在直接就点进去了前端页面，如何设置一个密码，只有自己能用？

**Comment by WenjiaRan** [comment]
可以nginx反代的时候，header里设置一个authorization校验

**Comment by akang943578** [comment]
可以有详细步骤吗，本人是个小白

**Comment by xiaozhou26** [comment]
https://github.com/aurora-develop/Duck2api#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

环境变量里面有Authorization=your_authorization  用户认证 key。
多看看文档再提issue吧
